config/routes.rb
Rails.application.routes.draw do
  resources :localizacaos
  resources :avaliacaos
  resources :usuarios
  resources :facebooks
  resources :comercios
  get 'welcome/index'

   root 'welcome#index'

end

app/models/facebook.rb
class Facebook < ActiveRecord::Base
end

app/controllers/facebooks_controller.rb
class FacebooksController < ApplicationController
  before_action :set_facebook, only: [:show, :edit, :update, :destroy]

  # GET /facebooks
  # GET /facebooks.json
  def index
    @facebooks = Facebook.all
  end

  # GET /facebooks/1
  # GET /facebooks/1.json
  def show
  end

  # GET /facebooks/new
  def new
    @facebook = Facebook.new
  end

  # GET /facebooks/1/edit
  def edit
  end

  # POST /facebooks
  # POST /facebooks.json
  def create
    @facebook = Facebook.new(facebook_params)

    respond_to do |format|
      if @facebook.save
        format.html { redirect_to @facebook, notice: 'Facebook was successfully created.' }
        format.json { render :show, status: :created, location: @facebook }
      else
        format.html { render :new }
        format.json { render json: @facebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facebooks/1
  # PATCH/PUT /facebooks/1.json
  def update
    respond_to do |format|
      if @facebook.update(facebook_params)
        format.html { redirect_to @facebook, notice: 'Facebook was successfully updated.' }
        format.json { render :show, status: :ok, location: @facebook }
      else
        format.html { render :edit }
        format.json { render json: @facebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facebooks/1
  # DELETE /facebooks/1.json
  def destroy
    @facebook.destroy
    respond_to do |format|
      format.html { redirect_to facebooks_url, notice: 'Facebook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facebook
      @facebook = Facebook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facebook_params
      params.require(:facebook).permit(:email, :senha)
    end
end

app/helpers/facebooks_helper.rb
module FacebooksHelper
end

app/views/facebooks/_form.html.haml
= simple_form_for(@facebook) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email
    = f.input :senha

  .form-actions
    = f.submit "Salvar"

app/views/facebooks/edit.html.haml
%h1 Editing facebook

= render 'form'

= link_to 'Show', @facebook
\|
= link_to 'Back', facebooks_path

app/views/facebooks/index.html.haml
%h1 Listing facebooks

%table
  %thead
    %tr
      %th Email
      %th Senha
      %th
      %th
      %th

  %tbody
    - @facebooks.each do |facebook|
      %tr
        %td= facebook.email
        %td= facebook.senha
        %td= link_to 'Show', facebook
        %td= link_to 'Edit', edit_facebook_path(facebook)
        %td= link_to 'Excluir', facebook, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Facebook', new_facebook_path

app/views/facebooks/new.html.haml
%h1 New facebook

= render 'form'

= link_to 'Back', facebooks_path

app/views/facebooks/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @facebook.email
%p
  %b Senha:
  = @facebook.senha

= link_to 'Edit', edit_facebook_path(@facebook)
\|
= link_to 'Back', facebooks_path