config/routes.rb
Rails.application.routes.draw do
  resources :localizacaos
  resources :avaliacaos
  resources :usuarios
  resources :facebooks
  resources :comercios
  get 'welcome/index'

   root 'welcome#index'

end

app/models/comercio.rb
class Comercio < ActiveRecord::Base
end

app/controllers/comercios_controller.rb
class ComerciosController < ApplicationController
  before_action :set_comercio, only: [:show, :edit, :update, :destroy]

  # GET /comercios
  # GET /comercios.json
  def index
    @comercios = Comercio.all
  end

  # GET /comercios/1
  # GET /comercios/1.json
  def show
  end

  # GET /comercios/new
  def new
    @comercio = Comercio.new
  end

  # GET /comercios/1/edit
  def edit
  end

  # POST /comercios
  # POST /comercios.json
  def create
    @comercio = Comercio.new(comercio_params)

    respond_to do |format|
      if @comercio.save
        format.html { redirect_to @comercio, notice: 'Comercio was successfully created.' }
        format.json { render :show, status: :created, location: @comercio }
      else
        format.html { render :new }
        format.json { render json: @comercio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comercios/1
  # PATCH/PUT /comercios/1.json
  def update
    respond_to do |format|
      if @comercio.update(comercio_params)
        format.html { redirect_to @comercio, notice: 'Comercio was successfully updated.' }
        format.json { render :show, status: :ok, location: @comercio }
      else
        format.html { render :edit }
        format.json { render json: @comercio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comercios/1
  # DELETE /comercios/1.json
  def destroy
    @comercio.destroy
    respond_to do |format|
      format.html { redirect_to comercios_url, notice: 'Comercio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comercio
      @comercio = Comercio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comercio_params
      params.require(:comercio).permit(:nome, :endereco, :tipo, :tefefone)
    end
end

app/helpers/comercios_helper.rb
module ComerciosHelper
end

app/views/comercios/_form.html.haml
= simple_form_for(@comercio) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nome
    = f.input :endereco, label: "Endereço"
    = f.input :tipo
    = f.input :tefefone, label: "Telefone"

  .form-actions
    = f.submit "Salvar"

app/views/comercios/edit.html.haml
%h1 Editar Comercio

= render 'form'

= link_to 'Show', @comercio
\|
= link_to 'Back', comercios_path

app/views/comercios/index.html.haml
%h1 Lista de Comercios

%table
  %thead
    %tr
      %th Nome
      %th Endereco
      %th Tipo
      %th Tefefone
      %th
      %th
      %th

  %tbody
    - @comercios.each do |comercio|
      %tr
        %td= comercio.nome
        %td= comercio.endereco
        %td= comercio.tipo
        %td= comercio.tefefone
        %td= link_to 'Show', comercio
        %td= link_to 'Edit', edit_comercio_path(comercio)
        %td= link_to 'Excluir', comercio, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Comercio', new_comercio_path

app/views/comercios/new.html.haml
%h1 New comercio

= render 'form'

= link_to 'Back', comercios_path

app/views/comercios/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @comercio.nome
%p
  %b Endereço:
  = @comercio.endereco
%p
  %b Tipo:
  = @comercio.tipo
%p
  %b Telefone:
  = @comercio.tefefone

= link_to 'Edit', edit_comercio_path(@comercio)
\|
= link_to 'Back', comercios_path