config/routes.rb
Rails.application.routes.draw do
  resources :localizacaos
  resources :avaliacaos
  resources :usuarios
  resources :facebooks
  resources :comercios
  get 'welcome/index'

   root 'welcome#index'

end

app/models/avaliacao.rb
class Avaliacao < ActiveRecord::Base
  belongs_to :comercio
end

app/controllers/avaliacaos_controller.rb
class AvaliacaosController < ApplicationController
  before_action :set_avaliacao, only: [:show, :edit, :update, :destroy]

  # GET /avaliacaos
  # GET /avaliacaos.json
  def index
    @avaliacaos = Avaliacao.all
  end

  # GET /avaliacaos/1
  # GET /avaliacaos/1.json
  def show
  end

  # GET /avaliacaos/new
  def new
    @avaliacao = Avaliacao.new
  end

  # GET /avaliacaos/1/edit
  def edit
  end

  # POST /avaliacaos
  # POST /avaliacaos.json
  def create
    @avaliacao = Avaliacao.new(avaliacao_params)

    respond_to do |format|
      if @avaliacao.save
        format.html { redirect_to @avaliacao, notice: 'Avaliacao was successfully created.' }
        format.json { render :show, status: :created, location: @avaliacao }
      else
        format.html { render :new }
        format.json { render json: @avaliacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /avaliacaos/1
  # PATCH/PUT /avaliacaos/1.json
  def update
    respond_to do |format|
      if @avaliacao.update(avaliacao_params)
        format.html { redirect_to @avaliacao, notice: 'Avaliacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @avaliacao }
      else
        format.html { render :edit }
        format.json { render json: @avaliacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avaliacaos/1
  # DELETE /avaliacaos/1.json
  def destroy
    @avaliacao.destroy
    respond_to do |format|
      format.html { redirect_to avaliacaos_url, notice: 'Avaliacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avaliacao
      @avaliacao = Avaliacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def avaliacao_params
      params.require(:avaliacao).permit(:alimentacao, :atendimento, :ambiente, :comercio_id)
    end
end

app/helpers/avaliacaos_helper.rb
module AvaliacaosHelper
end

app/views/avaliacaos/_form.html.haml
= simple_form_for(@avaliacao) do |f|
  = f.error_notification

  .form-inputs
    = f.input :alimentacao, label: "Alimentação"
    = f.input :atendimento
    = f.input :ambiente
    = f.association :comercio, label_method: :nome

  .form-actions
    = f.submit "Salvar"

app/views/avaliacaos/edit.html.haml
%h1 Editing avaliacao

= render 'form'

= link_to 'Show', @avaliacao
\|
= link_to 'Back', avaliacaos_path

app/views/avaliacaos/index.html.haml
%h1 Listing avaliacaos

%table
  %thead
    %tr
      %th Alimentacao
      %th Atendimento
      %th Ambiente
      %th Comercio
      %th
      %th
      %th

  %tbody
    - @avaliacaos.each do |avaliacao|
      %tr
        %td= avaliacao.alimentacao
        %td= avaliacao.atendimento
        %td= avaliacao.ambiente
        %td= avaliacao.comercio.nome
        %td= link_to 'Show', avaliacao
        %td= link_to 'Edit', edit_avaliacao_path(avaliacao)
        %td= link_to 'Excluir', avaliacao, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Avaliacao', new_avaliacao_path

app/views/avaliacaos/new.html.haml
%h1 New avaliacao

= render 'form'

= link_to 'Back', avaliacaos_path

app/views/avaliacaos/show.html.haml
%p#notice= notice

%p
  %b Alimentação:
  = @avaliacao.alimentacao
%p
  %b Atendimento:
  = @avaliacao.atendimento
%p
  %b Ambiente:
  = @avaliacao.ambiente
%p
  %b Comercio:
  = @avaliacao.comercio.nome

= link_to 'Edit', edit_avaliacao_path(@avaliacao)
\|
= link_to 'Back', avaliacaos_path